### ISSUE TITLE
output size doesn't match "paper" setting

### ISSUE THREAD

**Issue by EdwardsMike** [melmothx/pdf-imposition-perl#3]
Hi! I'm trying to impose 4 letter-size pages 2-up on 18" x 12", so am using 2up schema. If I pass no paper option, it imposes fine on 17" x 11", but when I pass paper as "18in:12in" the end result is actually on 36" x 12". Why is that and how can I get around it?

Also, I don't suppose there's a way to impose subsets of pages as opposed to all pages in the document? For instance, the first 4 pages imposed 2up, then the next 4 pages imposed 2up, and so on. (I am going to look into doing it with API::PDF2, but I'm not sure how to place a page at specific coordinates of the main PDF.)

**Comment by melmothx** [comment]
Mike Edwards ***@***.***> writes:

> Hi! I'm trying to impose 4 letter-size pages 2-up on 18" x 12", so am
> using 2up schema. If I pass no paper option, it imposes fine on 17" x
> 11", but when I pass paper as "18in:12in" the end result is actually
> on 36" x 12". Why is that and how can I get around it?

Hi.

I don't think that's a bug. The paper option is explained here:

https://metacpan.org/pod/PDF::Imposition


Passing this option triggers the cropmarks. While the original
dimensions are left unchanged, this size represents the size of the
logical page which is actually imposed.

For example, you have a PDF in a6, you pass a5 as paper, and schema 2up,
you are going to get an a4 with 2 a6 with cropmarks.


> Also, I don't suppose there's a way to impose subsets of pages as
> opposed to all pages in the document? For instance, the first 4 pages
> imposed 2up, then the next 4 pages imposed 2up, and so on. (I am going
> to look into doing it with API::PDF2, but I'm not sure how to place a
> page at specific coordinates of the main PDF.)

I think you're looking for the signature option:

https://metacpan.org/pod/PDF::Imposition::Schema2up

So I believe you're hitting this: If no signature is specified, the
whole text will be imposed on a single signature, regardeless of its
size.

I hope this helps.

-- 
Marco

**Comment by EdwardsMike** [comment]
Thanks for the quick response. After posting, I figured out that I shouldn't be passing the final sheet size (18x12) upon which the 2up would be imposed (which is how I read "this size represents the size of the logical page"), but rather half that (9x12).
I have also since figured out how to do what I want with PDF::API2. The downside is that I'll have to work out my own cropmarks.

**Comment by melmothx** [comment]
Ok, closing the issue then. Feel free to reopen in case.
